# Generated by Django 3.2.5 on 2021-07-08 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidadResponsable', models.CharField(max_length=50)),
                ('tituloEvento', models.CharField(max_length=50)),
                ('descripcionEvento', models.TextField()),
                ('eventoDedicadoA', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='')),
                ('fechaEvento', models.DateField()),
                ('inicioEvento', models.TimeField()),
                ('finEvento', models.TimeField()),
                ('sede', models.CharField(max_length=100)),
                ('cupo', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('creditos', models.DecimalField(decimal_places=2, max_digits=3)),
                ('categorias', models.CharField(max_length=50)),
            ],
        ),
    ]
