# Generated by Django 3.2.5 on 2021-10-02 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_auto_20210708_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='categorias',
            field=models.CharField(max_length=50, verbose_name='categorias'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='creditos',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='creditos'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='cupo',
            field=models.IntegerField(verbose_name='cupo'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='descripcion',
            field=models.TextField(verbose_name='descripcion'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='descripcionEvento',
            field=models.TextField(verbose_name='descripcionEvento'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='eventoDedicadoA',
            field=models.CharField(max_length=50, verbose_name='eventoDedicadoA'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='fechaEvento',
            field=models.DateField(verbose_name='fechaEvento'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='finEvento',
            field=models.TimeField(verbose_name='finEvento'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='inicioEvento',
            field=models.TimeField(verbose_name='inicioEvento'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='sede',
            field=models.CharField(max_length=100, verbose_name='sede'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='tituloEvento',
            field=models.CharField(default='', max_length=50, verbose_name='tituloEvento'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='unidadResponsable',
            field=models.CharField(default='', max_length=50, verbose_name='unidadResponsable'),
        ),
    ]
