# Generated by Django 3.2.5 on 2021-10-10 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_auto_20211001_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='eventosCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('color', models.CharField(max_length=20, verbose_name='color')),
                ('start', models.DateField(verbose_name='start')),
                ('end', models.DateField(verbose_name='end')),
                ('details', models.CharField(max_length=60, verbose_name='details')),
                ('timeStart', models.TimeField(verbose_name='timeStart')),
                ('timeEnd', models.TimeField(verbose_name='timeEnd')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.eventos')),
            ],
        ),
    ]
