# Generated by Django 3.2.5 on 2023-06-22 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0012_catalogo_civismo_catalogo_registro_civismo'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo_registro_civismo',
            name='catalogo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.catalogo_civismo'),
        ),
    ]
