# Generated by Django 3.2.5 on 2023-06-24 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0015_auto_20230624_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='catalogo_categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('clasificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.clasifi_cat')),
            ],
        ),
        migrations.CreateModel(
            name='catalogo_categorias2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('catalogo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.catalogo_categorias')),
            ],
        ),
    ]
