# Generated by Django 3.2.5 on 2023-08-26 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0021_alter_catalogo_categorias_objetivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='categorias',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='eventos.clasifi_cat'),
        ),
    ]
