# Generated by Django 3.2.5 on 2023-08-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0022_alter_eventos_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='responsable',
            field=models.CharField(default=1999, max_length=150, verbose_name='responsable'),
            preserve_default=False,
        ),
    ]
