# Generated by Django 3.2.5 on 2023-09-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0024_alter_eventos_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventossubirevidenciasalumno',
            name='alumno',
            field=models.CharField(max_length=9, verbose_name='cve_alumno'),
        ),
    ]
