# Generated by Django 3.2.5 on 2023-09-26 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0025_alter_eventossubirevidenciasalumno_alumno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventossubirevidenciasalumno',
            old_name='alumno',
            new_name='cve_alumno',
        ),
    ]
