# Generated by Django 3.2.5 on 2023-11-03 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0026_rename_alumno_eventossubirevidenciasalumno_cve_alumno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='fechaEvento',
        ),
    ]
