# Generated by Django 3.2.5 on 2023-11-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0028_auto_20231103_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='fechaFin',
            field=models.DateTimeField(verbose_name='fechaFin'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='fechaInicio',
            field=models.DateField(verbose_name='fechaInicio'),
        ),
    ]
