# Generated by Django 3.2.5 on 2023-11-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0029_auto_20231103_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='finEvento',
            field=models.TimeField(blank=True, null=True, verbose_name='finEvento'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='inicioEvento',
            field=models.TimeField(blank=True, null=True, verbose_name='inicioEvento'),
        ),
    ]
