# Generated by Django 3.2.5 on 2023-11-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0031_alter_eventos_fechafin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='fechaFin',
            field=models.DateField(blank=True, null=True, verbose_name='fechaFin'),
        ),
    ]
