# Generated by Django 3.2.5 on 2024-01-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0032_alter_eventos_fechafin'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='contacto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='contacto'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='horas_totales',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='horas_totales'),
        ),
    ]
