# Generated by Django 3.2.5 on 2024-01-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0033_auto_20240116_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='horas_totales',
            field=models.IntegerField(blank=True, null=True, verbose_name='Horas_totales'),
        ),
    ]
