# Generated by Django 3.2.5 on 2024-03-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0035_auto_20240227_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='cveUnidadResponsable',
            field=models.CharField(default='', max_length=150, verbose_name='unidadResponsable_id'),
        ),
        migrations.AlterField(
            model_name='eventossubirevidenciasalumno',
            name='img',
            field=models.FileField(upload_to='EvidenciasAlumnos/images'),
        ),
    ]
