# Generated by Django 3.2.5 on 2024-08-15 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0041_eventos_cve_ciclo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='cve_ciclo',
        ),
    ]
