# Generated by Django 3.2.5 on 2024-08-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0043_eventos_cve_ciclo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='cve_ciclo',
            field=models.CharField(max_length=100, verbose_name='cve_ciclo'),
        ),
    ]
