# Generated by Django 3.2.5 on 2024-08-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0044_alter_eventos_cve_ciclo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='cve_ciclo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='cve_ciclo'),
        ),
    ]
