# Generated by Django 3.2.5 on 2021-09-30 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_auto_20210708_1411'),
        ('FormacionIntegral', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formacionintegral',
            name='asistencia',
            field=models.IntegerField(null=True, verbose_name='asistencia'),
        ),
        migrations.AlterField(
            model_name='formacionintegral',
            name='evento_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.eventos', verbose_name='evento'),
        ),
    ]
