# Generated by Django 3.2.5 on 2021-10-05 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0002_alter_alumnos_carrera'),
        ('eventos', '0007_auto_20211001_2145'),
        ('FormacionIntegral', '0004_auto_20211004_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formacionintegral',
            name='alumno_id',
        ),
        migrations.RemoveField(
            model_name='formacionintegral',
            name='evento_id',
        ),
        migrations.AddField(
            model_name='formacionintegral',
            name='alumno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Alumnos.alumnos', verbose_name='alumno'),
        ),
        migrations.AddField(
            model_name='formacionintegral',
            name='evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.eventos', verbose_name='evento'),
        ),
    ]
