# Generated by Django 3.2.5 on 2021-11-05 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormacionIntegral', '0007_alter_formacionintegral_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formacionintegral',
            name='asistencia',
            field=models.IntegerField(default=0, null=True, verbose_name='asistencia'),
        ),
    ]
