# Generated by Django 3.2.5 on 2023-05-12 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormacionIntegral', '0008_alter_formacionintegral_asistencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formacionintegral',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='nombre'),
        ),
    ]
