# Generated by Django 3.2.5 on 2021-09-30 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0006_auto_20210708_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormacionIntegral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('matricula', models.IntegerField(verbose_name='matricula')),
                ('asistencia', models.IntegerField(verbose_name='asistencia')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('evento_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.eventos', verbose_name='evento_id')),
            ],
        ),
    ]
