# Generated by Django 3.2.5 on 2021-10-04 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0002_alter_alumnos_carrera'),
        ('FormacionIntegral', '0002_auto_20210929_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='formacionintegral',
            name='alumno_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Alumnos.alumnos', verbose_name='alumno'),
        ),
    ]
