# Generated by Django 3.2.5 on 2021-10-05 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormacionIntegral', '0006_auto_20211004_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formacionintegral',
            name='matricula',
            field=models.CharField(max_length=10, verbose_name='matricula'),
        ),
    ]
