# Generated by Django 3.2.5 on 2023-09-21 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0011_auto_20230913_1920'),
        ('FormacionIntegral', '0009_alter_formacionintegral_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formacionintegral',
            name='alumno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Alumnos.alumnos', verbose_name='alumno_id'),
        ),
    ]
