# Generated by Django 3.2.5 on 2021-10-01 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50, verbose_name='nombres')),
                ('apellidos', models.CharField(max_length=50, verbose_name='apellidos')),
                ('matricula', models.CharField(max_length=30, verbose_name='matricula')),
                ('carrera', models.CharField(max_length=30, verbose_name='asistencia')),
                ('semestre', models.IntegerField(verbose_name='semestre')),
                ('correo', models.EmailField(max_length=30, verbose_name='correo')),
                ('contraseña', models.CharField(max_length=50, verbose_name='contraseña')),
                ('img', models.ImageField(upload_to='Alumnos/images')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
