# Generated by Django 3.2.5 on 2021-10-01 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='carrera',
            field=models.CharField(max_length=30, verbose_name='carrera'),
        ),
    ]
