# Generated by Django 3.2.5 on 2023-09-06 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0003_auto_20230511_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnos',
            name='semestre',
        ),
    ]
