# Generated by Django 3.2.5 on 2023-09-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0008_auto_20230912_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cve_escuela',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_coordinator',
            field=models.BooleanField(default=False),
        ),
    ]
