# Generated by Django 3.2.5 on 2023-09-13 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0009_auto_20230913_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cve_escuela',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_coordinator',
        ),
    ]
