# Generated by Django 3.2.5 on 2023-10-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0011_auto_20230913_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cve_carrera',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
