# Generated by Django 3.2.5 on 2023-10-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0012_customuser_cve_carrera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cve_carrera',
            field=models.IntegerField(null=True),
        ),
    ]
