# Generated by Django 3.2.5 on 2021-07-08 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_alter_eventos_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='imagen',
        ),
    ]
