# Generated by Django 3.2.5 on 2021-07-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_remove_eventos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='tituloEvento',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='unidadResponsable',
            field=models.CharField(default='', max_length=50),
        ),
    ]
