# Generated by Django 3.2.5 on 2023-05-12 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0010_eventossubirevidenciasalumno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='categorias',
            field=models.CharField(max_length=100, verbose_name='categorias'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='eventoDedicadoA',
            field=models.CharField(max_length=200, verbose_name='eventoDedicadoA'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='sede',
            field=models.CharField(max_length=150, verbose_name='sede'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='tituloEvento',
            field=models.CharField(default='', max_length=200, verbose_name='tituloEvento'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='unidadResponsable',
            field=models.CharField(default='', max_length=150, verbose_name='unidadResponsable'),
        ),
        migrations.AlterField(
            model_name='eventoscalendario',
            name='color',
            field=models.CharField(max_length=100, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='eventoscalendario',
            name='details',
            field=models.CharField(max_length=250, verbose_name='details'),
        ),
        migrations.AlterField(
            model_name='eventoscalendario',
            name='end',
            field=models.CharField(max_length=200, verbose_name='end'),
        ),
        migrations.AlterField(
            model_name='eventoscalendario',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='eventoscalendario',
            name='start',
            field=models.CharField(max_length=200, verbose_name='start'),
        ),
    ]
