# Generated by Django 3.2.5 on 2023-06-24 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0014_catalogo_ciencia_catalogo_deporte_categorias_ciencia_categorias_deporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='clasifi_cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='catalogo_ciencia',
            name='clasificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.clasifi_cat'),
        ),
        migrations.AddField(
            model_name='catalogo_civismo',
            name='clasificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.clasifi_cat'),
        ),
        migrations.AddField(
            model_name='catalogo_deporte',
            name='clasificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.clasifi_cat'),
        ),
    ]
