# Generated by Django 3.2.5 on 2023-06-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0016_catalogo_categorias_catalogo_categorias2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogo_civismo',
            name='clasificacion',
        ),
        migrations.RemoveField(
            model_name='catalogo_deporte',
            name='clasificacion',
        ),
        migrations.RemoveField(
            model_name='catalogo_registro_civismo',
            name='catalogo',
        ),
        migrations.RemoveField(
            model_name='categorias_ciencia',
            name='catalogo',
        ),
        migrations.RemoveField(
            model_name='categorias_deporte',
            name='catalogo',
        ),
        migrations.AddField(
            model_name='eventos',
            name='subCategoria',
            field=models.CharField(max_length=100, null=True, verbose_name='subCategoria'),
        ),
        migrations.DeleteModel(
            name='catalogo_ciencia',
        ),
        migrations.DeleteModel(
            name='catalogo_civismo',
        ),
        migrations.DeleteModel(
            name='catalogo_deporte',
        ),
        migrations.DeleteModel(
            name='catalogo_registro_civismo',
        ),
        migrations.DeleteModel(
            name='categorias_ciencia',
        ),
        migrations.DeleteModel(
            name='categorias_deporte',
        ),
    ]
