# Generated by Django 3.2.5 on 2023-07-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0019_auto_20230627_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo_categorias',
            name='objetivo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
