# Generated by Django 3.2.5 on 2023-07-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0020_catalogo_categorias_objetivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo_categorias',
            name='objetivo',
            field=models.TextField(null=True),
        ),
    ]
